@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Nov 19 12:09:36 +0100 2021
=======
REM Generated by Vivado on Fri Nov 26 22:03:33 +0100 2021
>>>>>>> ecae7d1a4ff4fca3063760d65812e209a657fce7
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 882a187ef73d46a8a1c3943d88e512d9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_rom_example_behav xil_defaultlib.tb_rom_example -log elaborate.log"
call xelab  -wto 882a187ef73d46a8a1c3943d88e512d9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_rom_example_behav xil_defaultlib.tb_rom_example -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
